/** General MIDI percussion map (GM2 range 35-87 where names are agreed). */
export const GM_DRUMS: Record<number, string> = {
  35: 'Acoustic bass drum',
  36: 'Bass drum',
  37: 'Side stick',
  38: 'Acoustic snare',
  39: 'Hand clap',
  40: 'Electric snare',
  41: 'Low floor tom',
  42: 'Closed hi-hat',
  43: 'High floor tom',
  44: 'Pedal hi-hat',
  45: 'Low tom',
  46: 'Open hi-hat',
  47: 'Low-mid tom',
  48: 'Hi-mid tom',
  49: 'Crash cymbal',
  50: 'High tom',
  51: 'Ride cymbal',
  52: 'Chinese cymbal',
  53: 'Ride bell',
  54: 'Tambourine',
  55: 'Splash cymbal',
  56: 'Cowbell',
  57: 'Crash cymbal 2',
  58: 'Vibraslap',
  59: 'Ride cymbal 2',
  60: 'Hi bongo',
  61: 'Low bongo',
  62: 'Mute hi conga',
  63: 'Open hi conga',
  64: 'Low conga',
  65: 'High timbale',
  66: 'Low timbale',
  67: 'High agogo',
  68: 'Low agogo',
  69: 'Cabasa',
  70: 'Maracas',
  71: 'Short whistle',
  72: 'Long whistle',
  73: 'Short guiro',
  74: 'Long guiro',
  75: 'Claves',
  76: 'Hi wood block',
  77: 'Low wood block',
  78: 'Mute cuica',
  79: 'Open cuica',
  80: 'Mute triangle',
  81: 'Open triangle',
  82: 'Shaker',
  83: 'Jingle bell',
  84: 'Bell tree',
  85: 'Castanets',
  86: 'Mute surdo',
  87: 'Open surdo',
};
